<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="DESKTOP-V98FR5C" name="com.tetonshop.main.SeleniumTestManager" tests="5" failures="0" timestamp="2023-05-26T21:05:00 BDT" time="42.777" errors="1">
  <testcase name="setUpTest" time="42.777" classname="com.tetonshop.main.SeleniumTestManager">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.tetonshop.main.SeleniumTestManager.setUpTest(SeleniumTestManager.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUpTest -->
  <system-out/>
  <testcase name="FAQ" time="0.000" classname="com.tetonshop.main.SeleniumTestManager">
    <skipped/>
  </testcase> <!-- FAQ -->
  <system-out/>
  <testcase name="Products" time="0.000" classname="com.tetonshop.main.SeleniumTestManager">
    <skipped/>
  </testcase> <!-- Products -->
  <system-out/>
  <testcase name="AboutUs_Contact" time="0.000" classname="com.tetonshop.main.SeleniumTestManager">
    <skipped/>
  </testcase> <!-- AboutUs_Contact -->
  <system-out/>
  <testcase name="Contact" time="0.000" classname="com.tetonshop.main.SeleniumTestManager">
    <skipped/>
  </testcase> <!-- Contact -->
  <system-out/>
</testsuite> <!-- com.tetonshop.main.SeleniumTestManager -->
